### ISSUE TITLE
Gulpfile needs a way to clean template folder

### ISSUE THREAD

**Issue by nathanchicken** [onedarnleyroad/generator-one-craft#2]
When you create a folder in `src/templates` and later change your mind, rename it, or whatever, there's no way to send this change through to the compiled craft templates folder.  As such people are going to end up with a lot of junk in their compiled folder, so we probably need some sort of cleaning / diffing tool.

This is a good idea for anything really - css, js, but we also have to be careful not to delete anything a user might want in their assets folder.

**Comment by johndwells** [comment]
Closing our since we're no longer running tasks on the `craft/templates` folder.
